version: '3'

services:
  mc:
    image: memcached

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sadkjghlwh498jksdghlk4wtywaeuht98434
      MYSQL_DATABASE: signal_server
    healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          timeout: 20sz
          retries: 10
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - "db"
      - "mc"
    environment:
      - MEMCACHE_LOCATION=mc
    command: bash -c "sleep 60 && python manage.py migrate && ./start.sh"
    # command: bash -c "sleep 60 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"