apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mc
  name: mc
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mc
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: mc
    spec:
      containers:
        - image: memcached
          name: mc
          resources: {}
      restartPolicy: Always
status: {}
